#!/bin/bash

UPID=`cat ~/animelib/tmp/pids/unicorn.pid`
RPID=`cat /var/run/redis/redis.pid`

cd ~

service nginx stop
service postgresql stop
kill -9 ${UPID}
kill -9 ${RPID}

cd animelib

git pull origin master
bundle install
service postgresql start
RAILS_ENV=production rails db:migrate
RAILS_ENV=production rails db:migrate
RAILS_ENV=production rails db:migrate
yarn
RAILS_ENV=production rails assets:precompile

redis-server /etc/redis/redis.conf
bundle exec unicorn -c config/unicorn.rb -D -E production
service nginx start
